### ISSUE TITLE
Need to throw a real error "onError()"

### ISSUE THREAD

**Issue by tgreyuk** [bmvantunes/angular-library-builder#131]
Hi Bruno,

Tom here :)  It would be good to throw a real error on build failure (angular-library-builder.ts ln 35). Currently pipelines still build successfully when errors are thrown.

cheers...

**Comment by bmvantunes** [comment]
Hi @tgreyuk :+1: 

Can you please try the new version - v1.5.12 ?

**Comment by tgreyuk** [comment]
nice!!!
