### ISSUE TITLE
tsconfig.json has duplicated key

### ISSUE THREAD

**Issue by sandman21dan** [bmvantunes/angular-library-builder#42]
tsconfig.json file has a duplicated key

    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "strictNullChecks": true,                             // <--------
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,

**Comment by bmvantunes** [comment]
Thank you for your report @sandman21dan
