### ISSUE TITLE
Importing @types/es6-shim breaks build:library

### ISSUE THREAD

**Issue by StephenMIdeagen** [bmvantunes/angular-library-builder#65]
Hi @bmvantunes,

When ever I import @types/es6-shim as a devDependency to my package.json the build process throws the following error;

> D:\Work\groove-aot>npm run build:library
> 
> @groove/core@0.0.31 build:library D:\Work\groove-aot
> nglb --rootDir src --outDir out
> 
> Error at D:/Work/groove-aot/node_modules/typescript/lib/lib.es2015.core.d.ts:21:14: Duplicate identifier 'PropertyKey'.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:6:14: Duplicate identifier 'PropertyKey'.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:10:5: All declarations of 'value' must have identical modifiers.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:248:5: All declarations of 'EPSILON' must have identical modifiers.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:283:5: All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:290:5: All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:346:5: All declarations of 'flags' must have identical modifiers.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:498:5: All declarations of 'prototype' must have identical modifiers.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:561:5: All declarations of 'size' must have identical modifiers.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:570:5: All declarations of 'prototype' must have identical modifiers.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:581:5: All declarations of 'size' must have identical modifiers.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:591:5: All declarations of 'prototype' must have identical modifiers.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:596:11: All declarations of 'WeakMap' must have identical type parameters.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:604:27: Type 'K' does not satisfy the constraint 'object'.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:605:57: Type 'K' does not satisfy the constraint 'object'.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:606:5: All declarations of 'prototype' must have identical modifiers.
> Error at D:/Work/groove-aot/node_modules/@types/es6-shim/index.d.ts:620:5: All declarations of 'prototype' must have identical modifiers.
>
> Unfortunately we were not able to build your library! :(`

Removing this dependency allows us to build the library however, without the required shim. Is there any chance you could account for this?

Cheers,
Stephen

**Comment by StephenMIdeagen** [comment]
Updating the tsconfig-ngc.json provided by yourself to the following allows the compilation to work as expected. 

>  {
>   "compilerOptions": {
>     "module": "es2015",
>     "target": "es5",
>     "emitDecoratorMetadata": true,
>     "experimentalDecorators": true,
>     "declaration": true,
>     "sourceMap": true,
>     "moduleResolution": "node",
>     "typeRoots": [
>       "node_modules/@types/"
>     ],
>     "types": [
>       "es6-shim"
>     ]
>   },
>   "angularCompilerOptions": {
>     "strictMetadataEmit": true,
>     "skipTemplateCodegen": true
>   }
> }

Is it possible to allow an an argument to allow a custom tsconfig?

**Comment by bmvantunes** [comment]
Hi @StephenMIdeagen,

I'm sorry that you got this error.
I will create an example project to understand the error and all possible solutions/problems/impacts.

Also, I would love to have your opinion on this one... Which option do you think is better?
1. handle everything "magically"
2. add a ```-p``` parameter to use a custom tsconfig file

**Comment by bmvantunes** [comment]
Hi @StephenMIdeagen,

The latest version that I published should solve the es6-shim problem without any changes on your part.

If it does not solve your problem, I have added a new option to override properties in the default tsconfig file.
For example, to override the module from "es2015" to something else, you can now create a override-tsconfig.json file like this (this works for every tsconfig property):
```json
{
  "compilerOptions": {
    "module": "Specify module code generation: "None", "CommonJS", "AMD", "System", "UMD", "ES6", or "ES2015""
  }
}
```

Then, you call nglb like this:
```bash
nglb --rootDir path/to/your/source --outDir path/to/dist --tsconfig path/to/your/override-tsconfig.json
```

Let me know if this solves your issue :+1:
