### ISSUE TITLE
Offer a possibility to modify tsconfig entries

### ISSUE THREAD

**Issue by phymous** [bmvantunes/angular-library-builder#70]
Hi @bmvantunes,

first of all, nice tool!

Please offer a possibility to modify tsconfig entries. In my particular situation I need to set the `module` option to `CommonJS` because with `es2015` the code does not get uglified with uglify-js.

**Comment by bmvantunes** [comment]
Hi @phymous,

Thank you very much for your words! 👍 

I'll add two options this weekend that should fit your needs.
1. ignore the default ```angular-library-builder``` tsconfig.json file, and use your own tsconfig.json file
2. extend the default ```angular-library-builder``` tsconfig.json file with the properties you want to add/override

**Comment by bmvantunes** [comment]
Hi @phymous,

With the latest release you can add a new flag (--tsconfig) to override the defaults.
Your override-tsconfig.json file can be something like:
```json
{
  "compilerOptions": {
    "module": "Specify module code generation: "None", "CommonJS", "AMD", "System", "UMD", "ES6", or "ES2015""
  }
}
```

Then, you call nglb like this:
```bash
nglb --rootDir path/to/your/source --outDir path/to/dist --tsconfig path/to/your/override-tsconfig.json
```

Let me know if this solves your issue :+1:

**Comment by phymous** [comment]
I just tested the update and it works fine. Thanks a lot, I appreciate it! +1

**Comment by bmvantunes** [comment]
Excellent news @phymous 
I really appreciate your feedback. If you have any feature/bug request, please let me know. 

In the meantime, I hope this tool helps you :+1:
