### ISSUE TITLE
All-in-one tool

### ISSUE THREAD

**Issue by phymous** [bmvantunes/angular-library-builder#76]
Hi @bmvantunes ,

so now I use nglb together with scripts for creating a new package.json, copying images and uglifying the code. I wonder if these steps of building an angular library could be all integrated in one tool, e.g. in nglb. Like an angular-cli for libraries.

What is your thought on this? Is that idea crazy? ;-)

**Comment by bmvantunes** [comment]
Hi @phymous,

Not crazy by any means!
I think the most important things we need in nglb at the moment are:
1. create a folder called bundles with umd modules
  * minified version mylibrary.umd.min.js
  * normal version mylibrary.umd.js
2. Like @angular/cli copy an assets folder to dist folder
  * this one, I think solves your images problem :)
3. add a command for initial scaffolding
  * basically run ```ng new your-library-name --style scss```
  * then change the package.json:
    * add a devDependency to ```angular-library-builder```
    * add a script ```"build:library": "nglb......"```
    * add a script ```"prepublish": "npm run build:library"```
    * add an entry to module(existing deploy), types(existing deploy), main(umd.min.js).

Do you agree with everything? :)

**Comment by phymous** [comment]
So far so good @bmvantunes!

1. I agree, a ready-to-use umd bundle option would be nice. Nevertheless, the dist folder should also contain the transpiled js files (the bundler of the respective ng project takes care of them).  The dist folder would contain a
* minified version nice-component.component.js.min
* normal version nice-component.component

3. I would also suggest to move @angular dependencies to the peerDependencies field in the package.json

**Comment by bmvantunes** [comment]
excellent @phymous :tada: 

Regarding number 1, I will "copy" the structure that @angular/* use :)

I'll do some POCs with webpack and rollup to understand which one is better for our use case...

I expect to have a ready to use version in about 3/4 weeks, depending on my availability :+1:

**Comment by bmvantunes** [comment]
We have now guidelines by the angular team on how to build libraries :+1: 
I have created a ticket with all the documentation for future reference #92

**Comment by bmvantunes** [comment]
Great news!!!!
Now the CLI version 6.0.0 now supports libraries
