### ISSUE TITLE
Dont ignore all typings by default

### ISSUE THREAD

**Issue by DanielSchuech** [bmvantunes/angular-library-builder#80]
You ve added the ignoring of all @types while compile time in v1.4.1. I think that this should not be the default case. When you install the typings of a library you want to use them. The case that someone has to ignore some installed typings, for whatever reason, is a special case. So i would suggest that the special case had to set `types: []` in their `tsconfig.json`

Especially in greater projects with the latest version of nglb you have to specify the typings two times: 
1) in `package.json` for installing
2) in `tsconfig.json` to let them load from nglb

Currently i ve pinned the nglb version to 1.4.0 to not do that. Please think about reverting 769f24175b577ab3198164b3d1c70d12a8a5c92c. I am not able to update nglb in the future for fixes or new features. I am also interested in  #76  ;)

Greetings,
Daniel

**Comment by bmvantunes** [comment]
Hi Daniel,

Thanks a lot for your feedback :)
Some people reported problems with es6-shim, it is a real problem in the types.
To solve that problem, I adopted the same default as @angular/cli

The compilation is failing for you at the moment?

Kind regards,
Bruno

**Comment by DanielSchuech** [comment]
Thanks for the fast reply and work!

I got errors because of the typings for libraries without typings havn't been loaded e.g. some module not found. The compilation has only failed with v1.4.1. The building was succesfull with v1.4.0 and now even with v1.4.2.
